### ISSUE TITLE
mycheckpoint on MySQL 5.5.13

### ISSUE THREAD

**Issue by GoogleCodeExporter** [markl17/mycheckpoint#20]
```
Background:
I installed mycheckpoint couple months ago, it worked very well on 5.1.42. 
Recently I upgraded to MySQL 5.5.13, and 'mycheckpiont' collapsed.  

What is the expected output? What do you see instead?
-- See below the error...
What is the output when running with the "--verbose --debug" options?
---------------
[root@dbh1 ~]# mycheckpoint -uroot -pxxxxxxxxx --skip-disable-bin-log 
--skip-check-replication --socket=/var/lib/mysql/mysql.sock --verbose --debug
Traceback (most recent call last):
  File "/usr/local/bin/mycheckpoint", line 22, in ?
    import MySQLdb
  File "/usr/lib64/python2.4/site-packages/MySQLdb/__init__.py", line 19, in ?
    import _mysql
ImportError: libmysqlclient_r.so.15: cannot open shared object file: No such 
file or directory


-------------
What version of the mycheckpoint are you using?
-- 208
What version of the MySQL are you using? (SELECT VERSION())
-- 5.5.13
On what operating system?
-- Red Hat Enterprise Linux Server release 5.5 (Tikanga)


Please provide any additional information below.

Thanks,
kizer.alex@gmail.com

```

Original issue reported on code.google.com by `kizer.a...@gmail.com` on 10 Jun 2011 at 8:44

**Comment by GoogleCodeExporter** [comment]
```
This is a dependency issue for python-mysqlDB rather than mycheckpoint. The 
python-mysql driver expects libmysqlclient 1.5 and finds 1.6

Since you're running RedHat, I would suggest that you install the MySQL-compat 
package, which includes libmysqlclient15.
Look for the "MySQL-shared-compat-5.5.13-1.rhel5.i386.rpm" package on 
http://dev.mysql.com/downloads/mysql/5.5.html#downloads after selecting RedHat 
packages.
```

Original comment by `shlomi.n...@gmail.com` on 11 Jun 2011 at 11:21
- Changed state: **NotABug**
- Removed labels: **Type-Defect**

**Comment by GoogleCodeExporter** [comment]
```
Hi Shlomi,

I've installed the program you told me, however I still have the following
error:
------------------------------------------------------------------------
[root@dbh1 ~]# rpm -ivh MySQL-shared-compat-5.5.13-1.rhel5.i386.rpm
Preparing...                ###########################################
[100%]
        package MySQL-shared-compat-5.5.13-1.rhel5.i386 is already installed

[root@dbh1 ~]# mycheckpoint -uroot -pxxxxxxxxx --skip-disable-bin-log
--skip-check-replication --s
ocket=/var/lib/mysql/mysql.sock --verbose --debug
Traceback (most recent call last):
  File "/usr/local/bin/mycheckpoint", line 22, in ?
    import MySQLdb
  File "/usr/lib64/python2.4/site-packages/MySQLdb/__init__.py", line 19, in
?
    import _mysql
ImportError: libmysqlclient_r.so.15: cannot open shared object file: No such
file or directory
```

Original comment by `kizer.a...@gmail.com` on 23 Jun 2011 at 10:17

**Comment by GoogleCodeExporter** [comment]
```
Hmmm.. this is strange. However, this is still not a mycheckpoint bug: you must 
resolve your dependency issue with python-mysqldb.

Are you using yum? up2date? Try and re-install python-mysqldb; otherwise check 
for the dependency packages.
```

Original comment by `shlomi.n...@gmail.com` on 25 Jun 2011 at 3:16
