### ISSUE TITLE
"Unknown column 'innodb_rows_read_psec' in 'field list'" error on start

### ISSUE THREAD

**Issue by GoogleCodeExporter** [markl17/mycheckpoint#27]
```
After installing mycheckpoint, creating mycheckpoint schema and granting 
privileges, mycheckpoint is not recording any data. All tables are created, but 
remain empty. Any idea what I am missing here?

Output with -v --debug:
-- mycheckpoint rev 208, build 201011041330. Copyright (c) 2009-2010 by Shlomi 
Noach
-- database is mycheckpoint
-- Non matching deployed revision. Will auto-deploy
-- metadata table created
-- numbers table created
-- charts_api table created
-- html_components table created
-- custom_query table created
-- custom_query_view created
-- Global status & variables recorded
-- Master and slave status recorded
-- OS CPU info recorded
-- OS load average info recorded
-- OS mem info recorded
-- OS mountpoints info recorded
-- OS page io activity recorded
-- status_variables table exists
-- alert_condition table created
-- alert table created
-- alert_pending table created
-- sv_latest view created
-- sv_diff view created
-- sv_sample view created
-- status_variables_aggregated_hour table exists
-- status_variables_aggregated_day table exists
-- sv_hour view created
-- sv_day view created
-- sv_param_change view created
(1054, "Unknown column 'innodb_rows_read_psec' in 'field list'")
Traceback (most recent call last):
  File "/usr/bin/mycheckpoint", line 4854, in ?
    deploy_schema()
  File "/usr/bin/mycheckpoint", line 4767, in deploy_schema
    create_status_variables_views_and_aggregations()
  File "/usr/bin/mycheckpoint", line 3864, in create_status_variables_views_and_aggregations
    create_report_views("""
  File "/usr/bin/mycheckpoint", line 3842, in create_report_views
    act_query(custom_query)
  File "/usr/bin/mycheckpoint", line 246, in act_query
    num_affected_rows = cursor.execute(query)
  File "build/bdist.linux-x86_64/egg/MySQLdb/cursors.py", line 174, in execute
  File "build/bdist.linux-x86_64/egg/MySQLdb/connections.py", line 36, in defaulterrorhandler
OperationalError: (1054, "Unknown column 'innodb_rows_read_psec' in 'field 
list'")
--
-- Re-execute with --verbose --debug for detailed message and strack trace.
--

Additional information:
OS: Centos 5.6
Mycheckpoint version: 208
MySQL version: 5.1.57
Python version: 2.4.3
MySQL-python: 1.2.3

```

Original issue reported on code.google.com by `tiim...@gmail.com` on 16 Jan 2012 at 2:58

**Comment by GoogleCodeExporter** [comment]
```
Thank you.
Is it possible your server does not have InnoDB installed?
Please consult either:
SHOW ENGINES;
or
SHOW GLOBAL VARIABLES LIKE 'have_innodb';

Please attach answer for both.
```

Original comment by `shlomi.n...@gmail.com` on 16 Jan 2012 at 3:50

**Comment by GoogleCodeExporter** [comment]
```
Innodb is indeed disabled in Mysql config (skip-innodb). Is this a problem?

Output of show engines:

+------------+---------+--------------------------------------------------------
--------+--------------+------+------------+
| Engine     | Support | Comment                                                
        | Transactions | XA   | Savepoints |
+------------+---------+--------------------------------------------------------
--------+--------------+------+------------+
| InnoDB     | NO      | Supports transactions, row-level locking, and foreign 
keys     | NULL         | NULL | NULL       |
| MRG_MYISAM | YES     | Collection of identical MyISAM tables                  
        | NO           | NO   | NO         |
| BLACKHOLE  | YES     | /dev/null storage engine (anything you write to it 
disappears) | NO           | NO   | NO         |
| CSV        | YES     | CSV storage engine                                     
        | NO           | NO   | NO         |
| MEMORY     | YES     | Hash based, stored in memory, useful for temporary 
tables      | NO           | NO   | NO         |
| FEDERATED  | NO      | Federated MySQL storage engine                         
        | NULL         | NULL | NULL       |
| ARCHIVE    | YES     | Archive storage engine                                 
        | NO           | NO   | NO         |
| MyISAM     | DEFAULT | Default engine as of MySQL 3.23 with great performance 
        | NO           | NO   | NO         |
+------------+---------+--------------------------------------------------------
--------+--------------+------+------------+

SHOW GLOBAL VARIABLES LIKE 'have_innodb':
| have_innodb   | DISABLED |


```

Original comment by `tiim...@gmail.com` on 16 Jan 2012 at 3:59

**Comment by GoogleCodeExporter** [comment]
```
It is a problem only for Issue 27 :)
Will write a fix for that shortly.
```

Original comment by `shlomi.n...@gmail.com` on 16 Jan 2012 at 4:07

**Comment by GoogleCodeExporter** [comment]
```
Thanks a lot Shlomi. Really looking forward using this!
```

Original comment by `tiim...@gmail.com` on 17 Jan 2012 at 9:35

**Comment by GoogleCodeExporter** [comment]
```
This issue was closed by revision r218.
```

Original comment by `shlomi.n...@gmail.com` on 17 Jan 2012 at 7:39
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
The fix is in revision 218.
The revision is not yet published -- but you can grab the source code directly 
at: 
http://mycheckpoint.googlecode.com/svn-history/r218/trunk/src/mycheckpoint.py

Some additions in this revision may not actually make it to the next release.
I expect a release within the next month or so.

If you just want the specific fix to revision 208, then add the following lines:

        "innodb_buffer_pool_read_ahead",
        "innodb_buffer_pool_read_ahead_evicted",
        "innodb_rows_read", 
        "innodb_rows_inserted", 
        "innodb_rows_updated", 
        "innodb_rows_deleted",

at the get_additional_status_variables() function (starting line 640). (Not 
providing a patch here)
```

Original comment by `shlomi.n...@gmail.com` on 17 Jan 2012 at 7:44

**Comment by GoogleCodeExporter** [comment]
```
fantastic. thanks a lot!
```

Original comment by `tiim...@gmail.com` on 25 Jan 2012 at 3:09
