### ISSUE TITLE
while deploying 231 on  5.5.33a-MariaDB-log, got this error message -- status_variables_aggregated_hour table exists (1146, "Table 'mycheckpoint.status_variables_aggregated_hour' doesn't exist")

### ISSUE THREAD

**Issue by GoogleCodeExporter** [markl17/mycheckpoint#45]
```
What steps will reproduce the problem?
1. status_variables_aggregated_hour table exists
2.
3.

What is the expected output? What do you see instead?
-- status_variables_aggregated_hour table exists
(1146, "Table 'mycheckpoint.status_variables_aggregated_hour' doesn't exist")

What is the output when running with the "--verbose --debug" options?
Traceback (most recent call last):
  File "mycheckpoint.py", line 2260, in create_status_variables_hour_aggregation_table
    act_query(query)
  File "mycheckpoint.py", line 247, in act_query
    num_affected_rows = cursor.execute(query)
  File "/usr/lib64/python2.6/site-packages/MySQLdb/cursors.py", line 166, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.6/site-packages/MySQLdb/connections.py", line 35, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1005, "Can't create table 
'mycheckpoint.status_variables_aggregated_hour' (errno: 139)")
-- status_variables_aggregated_hour table exists
(1146, "Table 'mycheckpoint.status_variables_aggregated_hour' doesn't exist")
Traceback (most recent call last):
  File "mycheckpoint.py", line 4950, in <module>
    deploy_schema()
  File "mycheckpoint.py", line 4847, in deploy_schema
    create_status_variables_views_and_aggregations()
  File "mycheckpoint.py", line 3914, in create_status_variables_views_and_aggregations
    upgrade_status_variables_hour_aggregation_table()
  File "mycheckpoint.py", line 2021, in upgrade_status_variables_hour_aggregation_table
    return upgrade_status_variables_aggregation_table("status_variables_aggregated_hour")
  File "mycheckpoint.py", line 1994, in upgrade_status_variables_aggregation_table
    existing_columns = [row["Field"] for row in get_rows(query, write_conn)]
  File "mycheckpoint.py", line 268, in get_rows
    cursor.execute(query)
  File "/usr/lib64/python2.6/site-packages/MySQLdb/cursors.py", line 166, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.6/site-packages/MySQLdb/connections.py", line 35, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1146, "Table 'mycheckpoint.status_variables_aggregated_hour' 
doesn't exist")


What version of the mycheckpoint are you using? 231
What version of the MySQL are you using? (SELECT VERSION())5.5.33a-MariaDB-log
What version of Python are you using? (python --version) Python 2.6.8

On what operating system? SUSE Linux Enterprise Server 11 (x86_64)
What is your sql_mode? (SELECT @@global.sql_mode)  NO_AUTO_CREATE_USER


Please provide any additional information below.

```

Original issue reported on code.google.com by `jayakuma...@gmail.com` on 17 Jul 2014 at 3:35

**Comment by GoogleCodeExporter** [comment]
```
Somewhat on another instance it has gone thru well with this step, but failed 
in [OperationalError: (1091, "Can't DROP 'pre_condition_eval'; check that 
column/key exists")]; realized that this table creation def did not have this 
column definition, but eventually it will be dropped and created another column 
monitored_host_condition_eval;  it went thru fine after a dummy column 
definition 'pre_condition_eval' has been added.

Now while running the data collection, I got the below error.. 
[OperationalError: (1054, "Unknown column 'binlogs_<hostname>.000148' in 'field 
list'")]; looks like fetch_status_variables() is not handling the value of 
global status variable= ‘BINLOG_SNAPSHOT_FILE’; I thought this tool is very 
handy to get a performance dashboard for a mariadb instance, but struggling to 
setup / data collect; please help me to get a data collection

-- mycheckpoint rev 231, build 201305231510. Copyright (c) 2009-2013 by Shlomi 
Noach
-- database is mon
-- Global status & variables recorded
-- Master and slave status recorded
-- OS CPU info recorded
-- OS load average info recorded
-- OS mem info recorded
-- OS mountpoints info recorded
-- OS page io activity recorded
(1054, "Unknown column 'binlogs_mariadb003.000148' in 'field list'")
Traceback (most recent call last):
  File "/usr/local/bin/mycheckpoint", line 5055, in <module>
    collect_status_variables()
  File "/usr/local/bin/mycheckpoint", line 4446, in collect_status_variables
    num_affected_rows = act_query(query)
  File "/usr/local/bin/mycheckpoint", line 254, in act_query
    num_affected_rows = cursor.execute(query)
  File "/usr/lib64/python2.6/site-packages/MySQLdb/cursors.py", line 166, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.6/site-packages/MySQLdb/connections.py", line 35, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'binlogs_<hostname>.000148' in 'field 
list'")
--
-- Re-execute with --verbose --debug for detailed message and stack trace.

```

Original comment by `jayakuma...@gmail.com` on 18 Jul 2014 at 10:48
