### ISSUE TITLE
Startup / initial schema creation fails (Illegal mix of collations for operation 'concat')

### ISSUE THREAD

**Issue by GoogleCodeExporter** [markl17/mycheckpoint#8]
```
What steps will reproduce the problem?

1. FreeBSD 8.0
2. MySQL 5.3.2
3. mycheckpoint rev 132, build 201006041210

What is the output when running with the "--verbose --debug" options?

 from sets import ImmutableSet
-- mycheckpoint rev 132, build 201006041210. Copyright (c) 2009-2010 by Shlomi 
Noach
-- database is mycheckpoint
-- Non matching deployed revision. Will auto-deploy
-- metadata table created
-- numbers table created
-- charts_api table created
-- Global status & variables recorded
-- Cannot read /proc/stat. Skipping
-- Cannot read /proc/loadavg. Skipping
-- Cannot read /proc/meminfo. Skipping
-- OS mountpoints info recorded
-- status_variables table created
-- custom_query table created
-- alert_condition table created
-- alert table created
-- alert_pending table created
-- sv_latest view created
-- sv_diff view created
-- sv_sample view created
-- sv_hour view created
-- sv_day view created
-- sv_param_change view created
-- report views created
-- 24/7 report view created
-- recent reports views created
-- sv_report_sample_recent_aggregated view created
-- reports minmax views created
-- report human views created
-- sv_report_chart_sample_timeseries view created
-- sv_report_chart_hour_timeseries view created
-- sv_report_chart_day_timeseries view created
-- report charts labels views created
-- dycharts views created
(1271, "Illegal mix of collations for operation 'concat'")
Traceback (most recent call last):
  File "/usr/local/bin/mycheckpoint", line 3670, in <module>
    deploy_schema()
  File "/usr/local/bin/mycheckpoint", line 3584, in deploy_schema
    create_status_variables_views()
  File "/usr/local/bin/mycheckpoint", line 3327, in create_status_variables_views
    create_report_google_chart_views(report_chart_views)
  File "/usr/local/bin/mycheckpoint", line 2332, in 
create_report_google_chart_views
    act_query(query)
  File "/usr/local/bin/mycheckpoint", line 147, in act_query
    num_affected_rows = cursor.execute(query)
  File "/usr/local/lib/python2.6/site-packages/MySQLdb/cursors.py", line 166, in 
execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.6/site-packages/MySQLdb/connections.py", line 35, 
in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1271, "Illegal mix of collations for operation 'concat'")
--
-- Make sure you have executed mycheckpoint with 'deploy' after last 
install/update.upgrade
--  If not, run again with same configuration, and add 'deploy'. e.g.:
--  mycheckpoint --host=my_host deploy
--

```

Original issue reported on code.google.com by `tomaz.muraus` on 6 Jun 2010 at 9:18

**Comment by GoogleCodeExporter** [comment]
```
Hi,
Can you verify your MySQL version?
Issue 
SELECT VERSION() 
from withing the mysql client

Thanks
```

Original comment by `shlomi.n...@gmail.com` on 7 Jun 2010 at 5:09

**Comment by GoogleCodeExporter** [comment]
```
Also, please attach output for
show global variables like '%char%';

thanks
```

Original comment by `shlomi.n...@gmail.com` on 7 Jun 2010 at 5:43

**Comment by GoogleCodeExporter** [comment]
```
This solve the installation, but I don't know if it breaks something else:


diff mycheckpoint mycheckpoint.orig
874,875c874,875
<             simple_encoding CHAR(62) CHARSET utf8 COLLATE utf8_bin,
<             service_url VARCHAR(128) CHARSET utf8 COLLATE utf8_bin
---
>             simple_encoding CHAR(62) CHARSET ascii COLLATE ascii_bin,
>             service_url VARCHAR(128) CHARSET ascii COLLATE ascii_bin

```

Original comment by `rene.can...@gmail.com` on 19 Jul 2010 at 6:39

**Comment by GoogleCodeExporter** [comment]
```
I am still unable to reproduce.
rene.cannano: 
- which version of MySQL are you using? 
- which OS?
- What's you sql_mode (SELECT @@global.sql_mode)?

Thank you
```

Original comment by `shlomi.n...@gmail.com` on 20 Jul 2010 at 1:13

**Comment by GoogleCodeExporter** [comment]
```
OK, I am able to reproduce on 5.5-m3.
Thank you
```

Original comment by `shlomi.n...@gmail.com` on 20 Jul 2010 at 1:38

**Comment by GoogleCodeExporter** [comment]
```
I find that the problem is with service_url alone. Will manually convert it to 
utf8 during CONCAT query.
```

Original comment by `shlomi.n...@gmail.com` on 20 Jul 2010 at 1:50
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Fixed in r172 (not yet released).
```

Original comment by `shlomi.n...@gmail.com` on 20 Jul 2010 at 1:53

**Comment by GoogleCodeExporter** [comment]
Original comment by `shlomi.n...@gmail.com` on 20 Jul 2010 at 1:54
- Changed state: **Fixed**
